// POSIX surface generator (plurnk#29 / plurnk-service#343): emits man/plurnk.1
// and completions/{plurnk.bash,_plurnk,plurnk.fish} from the ONE source of
// truth — the exported USAGE text. Deterministic; run via npm run build:posix.
import { mkdir, writeFile, readFile } from "node:fs/promises";
import { USAGE } from "../src/dispatcher.ts";
import { renderCommandReference } from "../src/commands.ts";

const pkg = JSON.parse(await readFile(new URL("../package.json", import.meta.url), "utf8"));

// ── Section split on USAGE's own markers ──
const envAt = USAGE.indexOf("\nenv (");
const optionsAt = USAGE.indexOf("\noptions:");
const subcommandsAt = USAGE.indexOf("\nsubcommands:");
if (envAt < 0 || optionsAt < 0 || subcommandsAt < 0) throw new Error("USAGE markers moved; update generate-posix.mjs");
const usageBlockEnd = USAGE.indexOf("\n\n");
const synopsis = USAGE.slice(0, usageBlockEnd).split("\n");
const description = USAGE.slice(usageBlockEnd, envAt).trim();
const envBlock = USAGE.slice(envAt + 1, optionsAt).trimEnd();
const optionsBlock = USAGE.slice(optionsAt + 1, subcommandsAt).trimEnd();
const subcommandsBlock = USAGE.slice(subcommandsAt + 1).trimEnd();

const flags = [...new Set([...optionsBlock.matchAll(/--[a-z][a-z0-9_-]*/g)].map((m) => m[0]))];
const subcommands = [...new Set(
    subcommandsBlock.split("\n").slice(1)
        .map((line) => /^  ([a-z]+)\b/.exec(line)?.[1])
        .filter((name) => name !== undefined),
)];

// ── man/plurnk.1 ──
const roffEscape = (text) => text
    .replaceAll("\\", "\\\\")
    .split("\n")
    .map((line) => /^[.']/.test(line) ? `\\&${line}` : line)
    .join("\n");
const nf = (text) => `.nf\n${roffEscape(text)}\n.fi`;
const man = `.TH PLURNK 1 "" "plurnk ${pkg.version}" "User Commands"
.SH NAME
plurnk \\- terminal client for the plurnk\\-service agentic daemon
.SH SYNOPSIS
${nf(synopsis.join("\n").replace(/^usage: /, ""))}
.SH DESCRIPTION
${roffEscape(description)}
.SH OPTIONS
${nf(optionsBlock.replace(/^options:\n/, ""))}
.SH SUBCOMMANDS
${nf(subcommandsBlock.replace(/^subcommands:\n/, ""))}
.SH INTERACTIVE COMMANDS
The no-argument interactive terminal accepts these slash commands:
${nf(renderCommandReference())}
.SH ENVIRONMENT
${nf(envBlock)}
.SH EXIT STATUS
.TP
.B 0
The loop concluded successfully (or the subcommand completed).
.TP
.B 3
The loop failed, timed out (\\-\\-timeout), or a script's worst op status was an error.
.TP
.B 143
Terminated by SIGTERM after emitting the partial record.
.SH FILES
.TP
.I $XDG_CONFIG_HOME/plurnk/.env
Operator configuration (model aliases, provider credentials, client defaults).
.SH SEE ALSO
plurnk\\-service(1), and the repository SPEC.md for the client contract.
`;

// ── completions ──
const bash = `# bash completion for plurnk (generated by scripts/generate-posix.mjs)
_plurnk() {
    local cur=\${COMP_WORDS[COMP_CWORD]}
    local flags="${flags.join(" ")}"
    local subs="${subcommands.join(" ")}"
    if [[ $cur == -* ]]; then
        COMPREPLY=($(compgen -W "$flags" -- "$cur"))
    elif [[ $COMP_CWORD -eq 1 ]]; then
        COMPREPLY=($(compgen -W "$subs" -- "$cur") $(compgen -f -- "$cur"))
    else
        COMPREPLY=($(compgen -f -- "$cur"))
    fi
}
complete -F _plurnk plurnk
`;
const zsh = `#compdef plurnk
# zsh completion for plurnk (generated by scripts/generate-posix.mjs)
local -a flags subs
flags=(${flags.join(" ")})
subs=(${subcommands.join(" ")})
if [[ $words[CURRENT] == -* ]]; then
    compadd -- $flags
elif (( CURRENT == 2 )); then
    compadd -- $subs
    _files
else
    _files
fi
`;
const fish = `# fish completion for plurnk (generated by scripts/generate-posix.mjs)
${subcommands.map((sub) => `complete -c plurnk -n __fish_use_subcommand -a ${sub}`).join("\n")}
${flags.map((flag) => `complete -c plurnk -l ${flag.slice(2)}`).join("\n")}
`;

await mkdir(new URL("../man", import.meta.url), { recursive: true });
await mkdir(new URL("../completions", import.meta.url), { recursive: true });
await writeFile(new URL("../man/plurnk.1", import.meta.url), man);
await writeFile(new URL("../completions/plurnk.bash", import.meta.url), bash);
await writeFile(new URL("../completions/_plurnk", import.meta.url), zsh);
await writeFile(new URL("../completions/plurnk.fish", import.meta.url), fish);
console.log(`man/plurnk.1 + completions generated (${flags.length} flags, ${subcommands.length} subcommands)`);
