# bash completion for plurnk (generated by scripts/generate-posix.mjs)
_plurnk() {
    local cur=${COMP_WORDS[COMP_CWORD]}
    local flags="--help --version --json --workspace --worker --tui-worker --model --effort --autostart --daemon-timeout-ms --daemon-stop-timeout-ms --oauth-timeout-ms --service-bin --project-root --yolo --auto --capabilities --env-file --env-file-if-exists --max-turns --timeout --files-items --preview-lines --history-entries --mermaid-timeout-ms --color --max-commands --status-stream --share --no-git --loop --turn --since --limit --provider --all --offset --width"
    local subs="models workspace log read effort capabilities render completion mcp skills a2a members env schedule script"
    local candidate
    COMPREPLY=()
    while IFS= read -r candidate; do
        COMPREPLY+=("$candidate")
    done < <(
        if [[ $cur == -* ]]; then
            compgen -W "$flags" -- "$cur"
        elif [[ $COMP_CWORD -eq 1 ]]; then
            compgen -W "$subs" -- "$cur"
            compgen -f -- "$cur"
        else
            compgen -f -- "$cur"
        fi
    )
}
complete -o filenames -F _plurnk plurnk
