# bash completion for plurnk (generated by scripts/generate-posix.mjs)
_plurnk() {
    local cur=${COMP_WORDS[COMP_CWORD]}
    local flags="--help --version --json --workspace --worker --model --reasoning --project-root --yolo --auto --flags --request_user_input --env-file --env-file-if-exists --max-turns --timeout --files-items --md --max-commands --no-git --loop --turn --since --limit --provider --all --offset --width"
    local subs="models workspace log reasoning render mcp script"
    if [[ $cur == -* ]]; then
        COMPREPLY=($(compgen -W "$flags" -- "$cur"))
    elif [[ $COMP_CWORD -eq 1 ]]; then
        COMPREPLY=($(compgen -W "$subs" -- "$cur") $(compgen -f -- "$cur"))
    else
        COMPREPLY=($(compgen -f -- "$cur"))
    fi
}
complete -F _plurnk plurnk
