# fish completion for plurnk (generated by scripts/generate-posix.mjs)
complete -c plurnk -n __fish_use_subcommand -a models
complete -c plurnk -n __fish_use_subcommand -a workspace
complete -c plurnk -n __fish_use_subcommand -a log
complete -c plurnk -n __fish_use_subcommand -a reasoning
complete -c plurnk -n __fish_use_subcommand -a capabilities
complete -c plurnk -n __fish_use_subcommand -a render
complete -c plurnk -n __fish_use_subcommand -a web
complete -c plurnk -n __fish_use_subcommand -a mcp
complete -c plurnk -n __fish_use_subcommand -a script
complete -c plurnk -l help
complete -c plurnk -l version
complete -c plurnk -l json
complete -c plurnk -l workspace
complete -c plurnk -l worker
complete -c plurnk -l model
complete -c plurnk -l reasoning
complete -c plurnk -l project-root
complete -c plurnk -l yolo
complete -c plurnk -l auto
complete -c plurnk -l policy
complete -c plurnk -l capabilities
complete -c plurnk -l env-file
complete -c plurnk -l env-file-if-exists
complete -c plurnk -l max-turns
complete -c plurnk -l timeout
complete -c plurnk -l files-items
complete -c plurnk -l md
complete -c plurnk -l max-commands
complete -c plurnk -l no-git
complete -c plurnk -l loop
complete -c plurnk -l turn
complete -c plurnk -l since
complete -c plurnk -l limit
complete -c plurnk -l provider
complete -c plurnk -l all
complete -c plurnk -l offset
complete -c plurnk -l width
